import type { AdminData } from "./types";

export const SEED_DATA: AdminData = {
  staff: [
    { id: "s1", name: "Ana Rivera", email: "ana@licencesinflorida.com", role: "Admin", active: true },
    { id: "s2", name: "Carlos Mendez", email: "carlos@licencesinflorida.com", role: "Manager", active: true },
    { id: "s3", name: "Sofia Patel", email: "sofia@licencesinflorida.com", role: "Specialist", active: true },
    { id: "s4", name: "James Ortiz", email: "james@licencesinflorida.com", role: "Specialist", active: true },
  ],
  customers: [
    {
      id: "c1",
      legalName: "Maria Elena Perez",
      preferredName: "Maria",
      dateOfBirth: "1985-04-12",
      phone: "(786) 555-0142",
      email: "maria.perez@email.com",
      residentialAddress: "8420 SW 24th St, Miami, FL 33155",
      idType: "Florida Driver License",
      idExpiration: "2027-04-12",
      ssnLast4: "4821",
      citizenshipStatus: "US Citizen",
      preferredLanguage: "Spanish",
      bestContactMethod: "WhatsApp",
      emergencyContact: "Luis Perez — (786) 555-0199",
      pipelineStage: "Submitted",
      assignedStaffId: "s2",
      createdAt: "2026-01-15",
      notes: "Opening Perfect Body LLC — Hialeah + Doral locations",
    },
    {
      id: "c2",
      legalName: "Dr. Anthony Ruiz",
      preferredName: "Tony",
      dateOfBirth: "1978-09-03",
      phone: "(305) 555-0177",
      email: "aruiz.md@clinicmail.com",
      residentialAddress: "1200 Brickell Ave #1802, Miami, FL 33131",
      idType: "Florida Driver License",
      idExpiration: "2028-09-03",
      ssnLast4: "9033",
      citizenshipStatus: "US Citizen",
      preferredLanguage: "English",
      bestContactMethod: "Email",
      emergencyContact: "Clinic Admin — (305) 555-0101",
      pipelineStage: "Correction Requested",
      assignedStaffId: "s3",
      createdAt: "2025-11-02",
      notes: "AHCA renewal + Medicare revalidation; deficiency letter received",
    },
    {
      id: "c3",
      legalName: "Jennifer Alvarez",
      preferredName: "Jen",
      dateOfBirth: "1990-01-22",
      phone: "(954) 555-0166",
      email: "jen@sunrisewellness.fl",
      residentialAddress: "450 NE 3rd Ave, Fort Lauderdale, FL 33301",
      idType: "Passport",
      idExpiration: "2029-01-22",
      ssnLast4: "2210",
      citizenshipStatus: "Permanent Resident",
      preferredLanguage: "English",
      bestContactMethod: "Phone",
      emergencyContact: "Mark Alvarez — (954) 555-0188",
      pipelineStage: "Documents Needed",
      assignedStaffId: "s4",
      createdAt: "2026-06-10",
      notes: "New IV infusion clinic — missing lease & floor plan",
    },
    {
      id: "c4",
      legalName: "Robert Chen",
      preferredName: "Rob",
      dateOfBirth: "1972-12-01",
      phone: "(407) 555-0133",
      email: "rchen@orlandofamily.health",
      residentialAddress: "900 N Orange Ave, Orlando, FL 32801",
      idType: "Florida Driver License",
      idExpiration: "2026-12-01",
      ssnLast4: "7744",
      citizenshipStatus: "US Citizen",
      preferredLanguage: "English",
      bestContactMethod: "Email",
      emergencyContact: "Office Manager — (407) 555-0111",
      pipelineStage: "Renewal Monitoring",
      assignedStaffId: "s2",
      createdAt: "2024-03-18",
      notes: "Active primary care — AHCA renewal due within 90 days",
    },
    {
      id: "c5",
      legalName: "Sofia Morales",
      preferredName: "Sofia",
      dateOfBirth: "1988-07-19",
      phone: "(786) 555-0120",
      email: "sofia@brickellmedspa.com",
      residentialAddress: "200 S Biscayne Blvd, Miami, FL 33131",
      idType: "Florida Driver License",
      idExpiration: "2027-07-19",
      ssnLast4: "5512",
      citizenshipStatus: "US Citizen",
      preferredLanguage: "Spanish",
      bestContactMethod: "WhatsApp",
      emergencyContact: "Practice Manager — (786) 555-0121",
      pipelineStage: "Inspection Pending",
      assignedStaffId: "s3",
      createdAt: "2026-03-01",
      notes: "City of Miami inspection requested — folio & invoice on file",
    },
  ],
  businesses: [
    {
      id: "b1",
      customerId: "c1",
      legalName: "Perfect Body LLC",
      dba: "Perfect Body Clinic",
      entityType: "LLC",
      floridaDocNumber: "L22000123456",
      ein: "88-1234567",
      dateEstablished: "2022-06-01",
      description: "Medical aesthetics and wellness clinic",
      industry: "Health Care Clinic",
      phone: "(786) 555-2000",
      email: "ops@perfectbody.fl",
      website: "https://perfectbody.fl",
      mailingAddress: "Same as Hialeah location",
      county: "Miami-Dade",
      municipality: "Hialeah",
      employees: 8,
      expectedOpening: "2026-09-01",
      operatingHours: "Mon–Fri 9am–6pm",
    },
    {
      id: "b2",
      customerId: "c2",
      legalName: "Ruiz Primary Care PA",
      dba: "Ruiz Care",
      entityType: "Corporation",
      floridaDocNumber: "P18000987654",
      ein: "81-9876543",
      dateEstablished: "2018-02-14",
      description: "Primary care medical practice",
      industry: "Primary Care",
      phone: "(305) 555-3000",
      email: "admin@ruizcare.com",
      website: "https://ruizcare.com",
      mailingAddress: "1200 Brickell Ave #100, Miami, FL 33131",
      county: "Miami-Dade",
      municipality: "Miami",
      employees: 12,
      expectedOpening: "2018-05-01",
      operatingHours: "Mon–Fri 8am–5pm",
    },
    {
      id: "b3",
      customerId: "c3",
      legalName: "Sunrise Wellness Infusions LLC",
      dba: "Sunrise IV",
      entityType: "LLC",
      floridaDocNumber: "L26000555111",
      ein: "99-5551112",
      dateEstablished: "2026-05-20",
      description: "IV infusion and hydration clinic",
      industry: "IV Infusion",
      phone: "(954) 555-4000",
      email: "hello@sunrisewellness.fl",
      website: "",
      mailingAddress: "Pending",
      county: "Broward",
      municipality: "Fort Lauderdale",
      employees: 4,
      expectedOpening: "2026-10-15",
      operatingHours: "Tue–Sat 10am–7pm",
    },
    {
      id: "b4",
      customerId: "c4",
      legalName: "Orlando Family Health Inc",
      dba: "Orlando Family Health",
      entityType: "Corporation",
      floridaDocNumber: "P19000333444",
      ein: "82-3334445",
      dateEstablished: "2019-08-01",
      description: "Family medicine clinic",
      industry: "Family Medicine",
      phone: "(407) 555-5000",
      email: "info@orlandofamily.health",
      website: "https://orlandofamily.health",
      mailingAddress: "900 N Orange Ave, Orlando, FL 32801",
      county: "Orange",
      municipality: "Orlando",
      employees: 15,
      expectedOpening: "2019-11-01",
      operatingHours: "Mon–Fri 7:30am–6pm",
    },
    {
      id: "b5",
      customerId: "c5",
      legalName: "Brickell Med Spa LLC",
      dba: "Brickell Med",
      entityType: "LLC",
      floridaDocNumber: "L23000777888",
      ein: "92-7778889",
      dateEstablished: "2023-01-10",
      description: "Medical spa and aesthetic services",
      industry: "Med Spa",
      phone: "(786) 555-6000",
      email: "frontdesk@brickellmedspa.com",
      website: "https://brickellmedspa.com",
      mailingAddress: "200 S Biscayne Blvd Ste 210, Miami, FL 33131",
      county: "Miami-Dade",
      municipality: "Miami",
      employees: 6,
      expectedOpening: "2023-04-01",
      operatingHours: "Mon–Sat 10am–7pm",
    },
  ],
  locations: [
    {
      id: "l1",
      businessId: "b1",
      customerId: "c1",
      name: "Hialeah Clinic",
      address: "1750 W 49th St, Hialeah, FL 33012",
      county: "Miami-Dade",
      city: "Hialeah",
      folio: "04-3022-001-0120",
      zoning: "C-2",
      zoningStatus: "Approved",
      certificateOfUse: "Active",
      localBusinessTax: "Active",
      fireInspection: "Passed",
      buildingInspection: "Passed",
      healthInspection: "Pending",
      leaseStart: "2026-02-01",
      leaseEnd: "2029-01-31",
      landlord: "Hialeah Plaza Holdings",
      squareFootage: 2200,
      openingStatus: "Preparing to open",
    },
    {
      id: "l2",
      businessId: "b1",
      customerId: "c1",
      name: "Doral Location",
      address: "8200 NW 36th St, Doral, FL 33166",
      county: "Miami-Dade",
      city: "Doral",
      folio: "35-3018-005-0030",
      zoning: "Business",
      zoningStatus: "In review",
      certificateOfUse: "Not started",
      localBusinessTax: "Not started",
      fireInspection: "Not requested",
      buildingInspection: "Not requested",
      healthInspection: "Not required",
      leaseStart: "2026-08-01",
      leaseEnd: "2029-07-31",
      landlord: "Doral Commerce Park LLC",
      squareFootage: 1800,
      openingStatus: "Lease signed",
    },
    {
      id: "l3",
      businessId: "b2",
      customerId: "c2",
      name: "Brickell Main",
      address: "1200 Brickell Ave #100, Miami, FL 33131",
      county: "Miami-Dade",
      city: "Miami",
      folio: "01-4138-000-0450",
      zoning: "Commercial",
      zoningStatus: "Approved",
      certificateOfUse: "Active",
      localBusinessTax: "Active",
      fireInspection: "Passed",
      buildingInspection: "Passed",
      healthInspection: "Passed",
      leaseStart: "2018-04-01",
      leaseEnd: "2027-03-31",
      landlord: "Brickell Tower Assoc",
      squareFootage: 3500,
      openingStatus: "Open",
    },
    {
      id: "l4",
      businessId: "b5",
      customerId: "c5",
      name: "Brickell Med Spa",
      address: "200 S Biscayne Blvd Ste 210, Miami, FL 33131",
      county: "Miami-Dade",
      city: "Miami",
      folio: "01-0203-000-2100",
      zoning: "Commercial",
      zoningStatus: "Approved",
      certificateOfUse: "Active — address change pending",
      localBusinessTax: "Active",
      fireInspection: "Scheduled",
      buildingInspection: "Passed",
      healthInspection: "N/A",
      leaseStart: "2023-03-01",
      leaseEnd: "2028-02-28",
      landlord: "Biscayne Centre LLC",
      squareFootage: 1600,
      openingStatus: "Open — inspection pending",
    },
  ],
  contacts: [
    { id: "ct1", businessId: "b1", name: "Maria Elena Perez", role: "Owner", phone: "(786) 555-0142", email: "maria.perez@email.com" },
    { id: "ct2", businessId: "b1", name: "Dr. Elena Vargas", role: "Medical director", phone: "(305) 555-0888", email: "evargas@md.fl", licenseNumber: "ME998877" },
    { id: "ct3", businessId: "b2", name: "Dr. Anthony Ruiz", role: "Owner", phone: "(305) 555-0177", email: "aruiz.md@clinicmail.com", licenseNumber: "ME445566" },
    { id: "ct4", businessId: "b5", name: "City of Miami Inspector Desk", role: "Administrator", phone: "(305) 416-1100", email: "inspections@miamigov.com" },
  ],
  licenses: [
    {
      id: "lic1",
      type: "AHCA Health Care Clinic License",
      category: "Health-Care Business",
      agency: "AHCA",
      jurisdiction: "State",
      holderCustomerId: "c1",
      businessId: "b1",
      locationId: "l1",
      licenseNumber: "Pending",
      applicationNumber: "AHCA-2026-88421",
      status: "In Process",
      issueDate: "",
      effectiveDate: "",
      expirationDate: "2027-08-15",
      renewalDeadline: "2027-06-16",
      renewalFrequency: "Biennial",
      fee: 666,
      amountPaid: 666,
      paymentDate: "2026-07-01",
      paymentMethod: "ACH",
      confirmationNumber: "PAY-8821",
      assignedStaffId: "s2",
      agencyPortalUrl: "https://ahca.myflorida.com",
      notes: "Initial clinic license — Hialeah",
      verificationDate: "",
      nextActionDate: "2026-08-20",
    },
    {
      id: "lic2",
      type: "AHCA Renewal",
      category: "Health-Care Business",
      agency: "AHCA",
      jurisdiction: "State",
      holderCustomerId: "c2",
      businessId: "b2",
      locationId: "l3",
      licenseNumber: "HCC-118822",
      applicationNumber: "AHCA-REN-2026-441",
      status: "In Process",
      issueDate: "2024-09-01",
      effectiveDate: "2024-09-01",
      expirationDate: "2026-09-01",
      renewalDeadline: "2026-07-03",
      renewalFrequency: "Biennial",
      fee: 666,
      amountPaid: 666,
      paymentDate: "2026-06-15",
      paymentMethod: "Card",
      confirmationNumber: "PAY-4410",
      assignedStaffId: "s3",
      agencyPortalUrl: "https://ahca.myflorida.com",
      notes: "Correction requested — financial ability docs",
      verificationDate: "2026-06-20",
      nextActionDate: "2026-08-05",
    },
    {
      id: "lic3",
      type: "Certificate of Use",
      category: "City / County",
      agency: "City of Miami",
      jurisdiction: "City",
      holderCustomerId: "c5",
      businessId: "b5",
      locationId: "l4",
      licenseNumber: "COU-2023-9912",
      applicationNumber: "COU-CHG-2026-12",
      status: "In Process",
      issueDate: "2023-04-01",
      effectiveDate: "2023-04-01",
      expirationDate: "2027-04-01",
      renewalDeadline: "2027-03-01",
      renewalFrequency: "Annual",
      fee: 185,
      amountPaid: 185,
      paymentDate: "2026-07-10",
      paymentMethod: "Check",
      confirmationNumber: "INV-55601",
      assignedStaffId: "s3",
      agencyPortalUrl: "https://www.miamigov.com",
      notes: "Address change — City of Miami inspection",
      verificationDate: "",
      nextActionDate: "2026-08-08",
    },
    {
      id: "lic4",
      type: "AHCA Health Care Clinic License",
      category: "Health-Care Business",
      agency: "AHCA",
      jurisdiction: "State",
      holderCustomerId: "c4",
      businessId: "b4",
      licenseNumber: "HCC-772211",
      applicationNumber: "",
      status: "Active",
      issueDate: "2024-11-01",
      effectiveDate: "2024-11-01",
      expirationDate: "2026-11-01",
      renewalDeadline: "2026-09-02",
      renewalFrequency: "Biennial",
      fee: 666,
      amountPaid: 666,
      paymentDate: "2024-10-15",
      paymentMethod: "ACH",
      confirmationNumber: "PAY-7722",
      assignedStaffId: "s2",
      agencyPortalUrl: "https://ahca.myflorida.com",
      notes: "Renewal monitoring — start at 150 days",
      verificationDate: "2026-06-01",
      nextActionDate: "2026-06-04",
    },
    {
      id: "lic5",
      type: "Medicare Enrollment",
      category: "Credentialing",
      agency: "CMS / PECOS",
      jurisdiction: "Federal",
      holderCustomerId: "c2",
      businessId: "b2",
      locationId: "l3",
      licenseNumber: "PTAN-445566",
      applicationNumber: "PECOS-2026-99",
      status: "In Process",
      issueDate: "2019-01-10",
      effectiveDate: "2019-01-10",
      expirationDate: "2026-12-31",
      renewalDeadline: "2026-10-01",
      renewalFrequency: "Revalidation",
      fee: 0,
      amountPaid: 0,
      paymentDate: "",
      paymentMethod: "",
      confirmationNumber: "",
      assignedStaffId: "s3",
      agencyPortalUrl: "https://pecos.cms.hhs.gov",
      notes: "Medicare revalidation in progress",
      verificationDate: "2026-07-01",
      nextActionDate: "2026-08-15",
    },
    {
      id: "lic6",
      type: "Local Business Tax Receipt",
      category: "City / County",
      agency: "Miami-Dade County",
      jurisdiction: "County",
      holderCustomerId: "c1",
      businessId: "b1",
      locationId: "l1",
      licenseNumber: "LBT-2026-44102",
      applicationNumber: "LBT-APP-902",
      status: "Active",
      issueDate: "2026-03-01",
      effectiveDate: "2026-03-01",
      expirationDate: "2027-09-30",
      renewalDeadline: "2027-09-01",
      renewalFrequency: "Annual",
      fee: 95,
      amountPaid: 95,
      paymentDate: "2026-02-28",
      paymentMethod: "Card",
      confirmationNumber: "MD-LBT-902",
      assignedStaffId: "s4",
      agencyPortalUrl: "https://www.miamidade.gov",
      notes: "",
      verificationDate: "2026-03-02",
      nextActionDate: "2027-08-01",
    },
  ],
  applications: [
    {
      id: "a1",
      licenseId: "lic1",
      customerId: "c1",
      businessId: "b1",
      locationId: "l1",
      title: "AHCA Initial — Perfect Body Hialeah",
      status: "Submitted",
      formName: "AHCA Health Care Clinic Application",
      formVersion: "2025-11",
      signatureRequired: true,
      signatureReceived: true,
      filingMethod: "Online portal",
      submissionDate: "2026-07-02",
      paymentCompleted: true,
      correctionDeadline: "",
      assignedStaffId: "s2",
      checklist: [
        { item: "Form completed", done: true },
        { item: "Client signature", done: true },
        { item: "Supporting docs attached", done: true },
        { item: "Internal review", done: true },
        { item: "Payment completed", done: true },
        { item: "Submission confirmation", done: true },
      ],
    },
    {
      id: "a2",
      licenseId: "lic2",
      customerId: "c2",
      businessId: "b2",
      locationId: "l3",
      title: "AHCA Renewal — Ruiz Primary Care",
      status: "Deficiency or correction received",
      formName: "AHCA Renewal Application",
      formVersion: "2026-01",
      signatureRequired: true,
      signatureReceived: true,
      filingMethod: "Online portal",
      submissionDate: "2026-06-18",
      paymentCompleted: true,
      correctionDeadline: "2026-08-10",
      assignedStaffId: "s3",
      checklist: [
        { item: "Form completed", done: true },
        { item: "Proof of financial ability", done: false },
        { item: "Bank statements (3 mo)", done: false },
        { item: "Resubmission", done: false },
      ],
    },
  ],
  deficiencies: [
    {
      id: "d1",
      applicationId: "a2",
      dateReceived: "2026-07-20",
      agency: "AHCA",
      itemsRequested: "Updated proof of financial ability; 3 months bank statements; organizational chart",
      responseDeadline: "2026-08-10",
      responsibleStaffId: "s3",
      dateResubmitted: "",
      outcome: "Open",
    },
  ],
  documents: [
    {
      id: "doc1",
      name: "Articles of Organization — Perfect Body LLC",
      type: "Articles of organization or incorporation",
      customerId: "c1",
      businessId: "b1",
      uploadedAt: "2026-01-20",
      effectiveDate: "2022-06-01",
      expirationDate: "",
      verifiedBy: "Carlos Mendez",
      verificationStatus: "Verified",
      confidentiality: "Internal",
      version: 1,
      notes: "Sunbiz filing",
    },
    {
      id: "doc2",
      name: "Lease — Hialeah Clinic",
      type: "Lease",
      customerId: "c1",
      businessId: "b1",
      locationId: "l1",
      uploadedAt: "2026-02-05",
      effectiveDate: "2026-02-01",
      expirationDate: "2029-01-31",
      verifiedBy: "Carlos Mendez",
      verificationStatus: "Verified",
      confidentiality: "Restricted",
      version: 1,
      notes: "",
    },
    {
      id: "doc3",
      name: "AHCA Deficiency Letter — Ruiz",
      type: "Deficiency letter",
      customerId: "c2",
      businessId: "b2",
      licenseId: "lic2",
      uploadedAt: "2026-07-20",
      effectiveDate: "2026-07-20",
      expirationDate: "2026-08-10",
      verifiedBy: "Sofia Patel",
      verificationStatus: "Pending",
      confidentiality: "Restricted",
      version: 1,
      notes: "Correction deadline Aug 10",
    },
    {
      id: "doc4",
      name: "City of Miami Inspection Invoice",
      type: "Payment receipt",
      customerId: "c5",
      businessId: "b5",
      locationId: "l4",
      uploadedAt: "2026-07-10",
      effectiveDate: "2026-07-10",
      expirationDate: "",
      verifiedBy: "Sofia Patel",
      verificationStatus: "Verified",
      confidentiality: "Internal",
      version: 1,
      notes: "INV-55601",
    },
  ],
  inspections: [
    {
      id: "ins1",
      type: "Certificate of Use / Zoning Inspection",
      agency: "City of Miami",
      businessId: "b5",
      locationId: "l4",
      customerId: "c5",
      permitNumber: "COU-CHG-2026-12",
      folio: "01-0203-000-2100",
      invoiceNumber: "INV-55601",
      requestedDate: "2026-07-08",
      scheduledDate: "2026-08-08T10:00",
      inspector: "TBD",
      onsiteContact: "Sofia Morales",
      fee: 185,
      paymentStatus: "Paid",
      result: "",
      violations: "",
      reinspectionRequired: false,
      status: "Scheduled",
    },
  ],
  providers: [
    {
      id: "p1",
      customerId: "c2",
      businessId: "b2",
      legalName: "Anthony Ruiz, MD",
      npi: "1234567890",
      taxonomy: "207Q00000X Family Medicine",
      flLicense: "ME445566",
      licenseExpiration: "2027-01-31",
      caqhId: "CAQH-998877",
      caqhReattestDate: "2026-09-15",
      medicarePtan: "PTAN-445566",
      pecosStatus: "Revalidation in progress",
      medicaidId: "FL-MD-88991",
      malpracticePolicy: "Active — expires 2026-12-01",
      credentialingStatus: "Additional information requested",
      payer: "Medicare / Blue Cross",
    },
    {
      id: "p2",
      customerId: "c1",
      businessId: "b1",
      legalName: "Elena Vargas, MD",
      npi: "1987654321",
      taxonomy: "207N00000X Dermatology",
      flLicense: "ME998877",
      licenseExpiration: "2028-05-31",
      caqhId: "CAQH-112233",
      caqhReattestDate: "2026-11-01",
      medicarePtan: "",
      pecosStatus: "Not started",
      medicaidId: "",
      malpracticePolicy: "Active",
      credentialingStatus: "Data requested",
      payer: "Multiple — pending",
    },
  ],
  tasks: [
    { id: "t1", title: "Upload updated bank statements — Ruiz AHCA", type: "Correct deficiency", customerId: "c2", businessId: "b2", applicationId: "a2", assignedStaffId: "s3", priority: "Urgent", dueDate: "2026-08-08", status: "In Progress", clientVisible: true, notes: "Deficiency deadline Aug 10" },
    { id: "t2", title: "Request lease & floor plan — Sunrise IV", type: "Request documents", customerId: "c3", businessId: "b3", assignedStaffId: "s4", priority: "High", dueDate: "2026-08-05", status: "Open", clientVisible: true, notes: "" },
    { id: "t3", title: "Confirm City of Miami inspection — Brickell Med", type: "Schedule inspection", customerId: "c5", businessId: "b5", assignedStaffId: "s3", priority: "High", dueDate: "2026-08-07", status: "Open", clientVisible: false, notes: "Folio + invoice on file" },
    { id: "t4", title: "Start AHCA renewal workflow — Orlando Family", type: "Prepare renewal", customerId: "c4", businessId: "b4", licenseId: "lic4", assignedStaffId: "s2", priority: "Medium", dueDate: "2026-08-15", status: "Open", clientVisible: false, notes: "150-day internal start" },
    { id: "t5", title: "Update medical director attestation — Perfect Body", type: "Update officer or director", customerId: "c1", businessId: "b1", assignedStaffId: "s2", priority: "Medium", dueDate: "2026-08-20", status: "Open", clientVisible: true, notes: "" },
    { id: "t6", title: "CAQH reattestation reminder — Dr. Ruiz", type: "Update payer information", customerId: "c2", assignedStaffId: "s3", priority: "Medium", dueDate: "2026-09-01", status: "Open", clientVisible: true, notes: "" },
  ],
  reminders: [
    { id: "r1", title: "AHCA renewal — Orlando Family (90 days)", relatedType: "license", relatedId: "lic4", dueDate: "2026-08-03", channel: "In-app", recipient: "Carlos Mendez", status: "Scheduled" },
    { id: "r2", title: "Deficiency response deadline — Ruiz", relatedType: "deficiency", relatedId: "d1", dueDate: "2026-08-10", channel: "Email", recipient: "Sofia Patel", status: "Scheduled" },
    { id: "r3", title: "City of Miami inspection appointment", relatedType: "inspection", relatedId: "ins1", dueDate: "2026-08-08", channel: "Calendar", recipient: "Sofia Morales", status: "Sent" },
    { id: "r4", title: "Lease expiring — Ruiz Brickell (check)", relatedType: "location", relatedId: "l3", dueDate: "2027-01-15", channel: "In-app", recipient: "Carlos Mendez", status: "Scheduled" },
    { id: "r5", title: "CAQH reattestation — Dr. Ruiz", relatedType: "provider", relatedId: "p1", dueDate: "2026-09-15", channel: "Email", recipient: "Anthony Ruiz", status: "Scheduled" },
  ],
  payments: [
    { id: "pay1", customerId: "c1", businessId: "b1", description: "AHCA initial filing + service", serviceFee: 1500, governmentFee: 666, inspectionFee: 0, amountPaid: 2166, balance: 0, paymentDate: "2026-07-01", method: "ACH", receipt: "PAY-8821", status: "Paid" },
    { id: "pay2", customerId: "c2", businessId: "b2", description: "AHCA renewal + service", serviceFee: 900, governmentFee: 666, inspectionFee: 0, amountPaid: 1566, balance: 0, paymentDate: "2026-06-15", method: "Card", receipt: "PAY-4410", status: "Paid" },
    { id: "pay3", customerId: "c5", businessId: "b5", description: "City of Miami inspection fee", serviceFee: 250, governmentFee: 0, inspectionFee: 185, amountPaid: 185, balance: 250, paymentDate: "2026-07-10", method: "Check", receipt: "INV-55601", status: "Partial" },
    { id: "pay4", customerId: "c3", businessId: "b3", description: "Startup licensing package deposit", serviceFee: 2500, governmentFee: 0, inspectionFee: 0, amountPaid: 0, balance: 2500, paymentDate: "", method: "", receipt: "", status: "Due" },
  ],
  templates: [
    {
      id: "tpl1",
      name: "General Florida Business Startup",
      category: "General Florida business",
      agency: "Multiple",
      jurisdiction: "State / Local",
      checklist: ["Sunbiz entity", "EIN", "Fictitious name / DBA", "DOR registration", "Sales tax certificate", "Local business tax", "Certificate of use", "Zoning", "Fire inspection", "CO"],
    },
    {
      id: "tpl2",
      name: "AHCA Health Care Clinic",
      category: "Health-care businesses",
      agency: "AHCA",
      jurisdiction: "State",
      checklist: ["AHCA application", "Clinic exemption check", "Medical/clinic director", "Level 2 screening", "Proof of financial ability", "Bank statements", "Liability insurance", "Org chart", "Employee/provider roster", "NPI", "Medicare/Medicaid"],
    },
    {
      id: "tpl3",
      name: "Miami-Dade Location Checklist",
      category: "City and county",
      agency: "Miami-Dade / Municipality",
      jurisdiction: "County / City",
      checklist: ["Zoning approval", "Certificate of use", "LBT", "Sewer / DER as applicable", "Fire inspection", "Building inspection", "Sign permit"],
    },
    {
      id: "tpl4",
      name: "Provider Credentialing Pack",
      category: "Credentialing",
      agency: "CMS / CAQH / Payers",
      jurisdiction: "Federal / Commercial",
      checklist: ["NPI", "FL professional license", "CAQH", "PECOS", "Medicare PTAN", "Medicaid ID", "Malpractice", "Payer applications", "Revalidation dates"],
    },
  ],
  agencies: [
    { id: "ag1", name: "AHCA", type: "State — Health facilities", portalUrl: "https://ahca.myflorida.com", notes: "Clinic licenses & renewals" },
    { id: "ag2", name: "DBPR", type: "State — Professions & businesses", portalUrl: "https://www.myfloridalicense.com", notes: "Apply, renew, verify licenses" },
    { id: "ag3", name: "Florida Department of Health", type: "State — Practitioners", portalUrl: "https://www.floridahealth.gov", notes: "Professional licenses, CE" },
    { id: "ag4", name: "Florida Department of Revenue", type: "State — Tax", portalUrl: "https://floridarevenue.com", notes: "Sales tax, business tax registration" },
    { id: "ag5", name: "Sunbiz / Division of Corporations", type: "State — Entity", portalUrl: "https://dos.fl.gov/sunbiz", notes: "Corp/LLC filings, annual report" },
    { id: "ag6", name: "CMS / PECOS", type: "Federal", portalUrl: "https://pecos.cms.hhs.gov", notes: "Medicare enrollment" },
    { id: "ag7", name: "Miami-Dade County", type: "County", portalUrl: "https://www.miamidade.gov", notes: "LBT, DER, local permits" },
    { id: "ag8", name: "City of Miami", type: "City", portalUrl: "https://www.miamigov.com", notes: "COU, inspections, zoning" },
    { id: "ag9", name: "City of Hialeah", type: "City", portalUrl: "https://www.hialeahfl.gov", notes: "Municipal COU / LBT" },
    { id: "ag10", name: "City of Doral", type: "City", portalUrl: "https://www.cityofdoral.com", notes: "Municipal permits" },
  ],
};

export const ADMIN_CREDENTIALS = {
  email: "admin@licencesinflorida.com",
  password: "Licenses2026!",
};
